services:
  web:
    build: .
    command: python manage.py runserver 0.0.0:8500
    volumes:
      - .:/app
    ports:
      - "8500:8500"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_temp:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      

volumes:
  postgres_temp:
